version: '2'
services:

  sshd:
    build: sshd
    volumes:
      - /git
    network_mode: bridge
    restart: unless-stopped

  smart-http:
    build: smart-http
    volumes:
      - /repos
      - /ng-auth
    environment:
      - FQDN=your.domain.com
      - VIRTUAL_HOST=your.domain.com
      - CERT_NAME=shared
    network_mode: bridge
    restart: unless-stopped
