version: '2'
services:

  sshd:
    build: sshd
    volumes:
      - git:/git:rw
    ports:
      - "22"
    network_mode: bridge
    restart: unless-stopped

  smart-http:
    build: smart-http
    volumes:
      - git:/repos:rw
    environment:
      - VIRTUAL_HOST=your.domain.com
      - CERT_NAME=shared
    network_mode: bridge
    restart: unless-stopped

volumes:
  git:
    driver_opts:
      type: none
      o: bind
      device: /data/git